/*
 * generated by Xtext 2.15.0
 */
package de.tu_bs.ccc.contracting.idl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class CidlUiModule extends AbstractCidlUiModule {
}
