/*
 * generated by Xtext 2.15.0
 */
package de.tu_bs.ccc.contracting.idl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CidlRuntimeModule extends AbstractCidlRuntimeModule {
}
