/*
 * generated by Xtext 2.15.0
 */
package de.tu_bs.ccc.contracting.idl.validation

import org.eclipse.xtext.validation.Check
import de.tu_bs.ccc.contracting.idl.cidl.ContractPair

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CidlValidator extends AbstractCidlValidator {
	
	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(ContractPair greeting) {
//		GrammarSolver gs = new GrammarSolver;
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					CidlPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
	
}
